//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saltyeyes.Cephalon.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Images {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Images() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Saltyeyes.Cephalon.Properties.Images", typeof(Images).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/PyWLqkC.png.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/LiymYKz.png.
        /// </summary>
        internal static string AxiExceptional {
            get {
                return ResourceManager.GetString("AxiExceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/sTePCMM.png.
        /// </summary>
        internal static string AxiFlawless {
            get {
                return ResourceManager.GetString("AxiFlawless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/HMABE0F.png.
        /// </summary>
        internal static string AxiIntact {
            get {
                return ResourceManager.GetString("AxiIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/hRdbn5e.png.
        /// </summary>
        internal static string AxiRadiant {
            get {
                return ResourceManager.GetString("AxiRadiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/0tI7gV2.png.
        /// </summary>
        internal static string Blast {
            get {
                return ResourceManager.GetString("Blast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/na2p9cN.png.
        /// </summary>
        internal static string Cold {
            get {
                return ResourceManager.GetString("Cold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/3PcThDY.png.
        /// </summary>
        internal static string Corrosive {
            get {
                return ResourceManager.GetString("Corrosive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/CObHrrM.png.
        /// </summary>
        internal static string Electricity {
            get {
                return ResourceManager.GetString("Electricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/w5jdPyv.png.
        /// </summary>
        internal static string Equal {
            get {
                return ResourceManager.GetString("Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/lSPedS4.png.
        /// </summary>
        internal static string Gas {
            get {
                return ResourceManager.GetString("Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/sLMxgcU.png.
        /// </summary>
        internal static string Heat {
            get {
                return ResourceManager.GetString("Heat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/zGuDiUW.png.
        /// </summary>
        internal static string Impact {
            get {
                return ResourceManager.GetString("Impact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/v2CSYqg.png.
        /// </summary>
        internal static string LithExceptional {
            get {
                return ResourceManager.GetString("LithExceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/ayGHBj0.png.
        /// </summary>
        internal static string LithFlawless {
            get {
                return ResourceManager.GetString("LithFlawless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/qQ82gUf.png.
        /// </summary>
        internal static string LithIntact {
            get {
                return ResourceManager.GetString("LithIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/LzuclrM.png.
        /// </summary>
        internal static string LithRadiant {
            get {
                return ResourceManager.GetString("LithRadiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/Phc0WWY.png.
        /// </summary>
        internal static string Magnetic {
            get {
                return ResourceManager.GetString("Magnetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/4xMtwx3.png.
        /// </summary>
        internal static string MesoExceptional {
            get {
                return ResourceManager.GetString("MesoExceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/8vH39Ki.png.
        /// </summary>
        internal static string MesoFlawless {
            get {
                return ResourceManager.GetString("MesoFlawless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/o1H518G.png.
        /// </summary>
        internal static string MesoIntact {
            get {
                return ResourceManager.GetString("MesoIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/C9bCppb.png.
        /// </summary>
        internal static string MesoRadiant {
            get {
                return ResourceManager.GetString("MesoRadiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/woIvEJH.png.
        /// </summary>
        internal static string NeoExceptional {
            get {
                return ResourceManager.GetString("NeoExceptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/1rWuu11.png.
        /// </summary>
        internal static string NeoFlawless {
            get {
                return ResourceManager.GetString("NeoFlawless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/1iHIouA.png.
        /// </summary>
        internal static string NeoIntact {
            get {
                return ResourceManager.GetString("NeoIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/zeOFgBy.png.
        /// </summary>
        internal static string NeoRadiant {
            get {
                return ResourceManager.GetString("NeoRadiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/HlLTqlt.png.
        /// </summary>
        internal static string Puncture {
            get {
                return ResourceManager.GetString("Puncture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/QEj4n6J.png.
        /// </summary>
        internal static string Radiation {
            get {
                return ResourceManager.GetString("Radiation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/04pQBXh.png.
        /// </summary>
        internal static string Slash {
            get {
                return ResourceManager.GetString("Slash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/lgPMBV6.png.
        /// </summary>
        internal static string Toxin {
            get {
                return ResourceManager.GetString("Toxin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://i.imgur.com/pT1vmFs.png.
        /// </summary>
        internal static string Viral {
            get {
                return ResourceManager.GetString("Viral", resourceCulture);
            }
        }
    }
}
